# -*- coding: utf-8 -*-
"""Собирает flavor-wheel/flavor-data.json: дерево колеса + тексты панели."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
TREE = json.loads((ROOT / "assets" / "flavor-tree-wheel.json").read_text(encoding="utf-8"))

CATEGORY_ORBIT = {
    "nutty-cocoa": ["chocolate-bar", "cocoa-powder", "hazelnut", "peanut", "walnut", "coconut", "almond", "pecan"],
    "sweet": ["honey", "caramel", "jam", "vanilla", "maple", "toffee", "nougat", "yogurt"],
    "floral-tea": ["rose", "jasmine", "lavender", "hibiscus", "mint", "tea-cup", "lemongrass", "chamomile"],
    "fruity": ["cherry", "strawberry", "lemon", "apple", "mango", "grape", "peach", "blueberry"],
    "spicy-unique": ["clove", "cinnamon-stick", "nutmeg", "peppercorn", "star-anise", "croissant", "wine-glass", "ginger"],
}

SUB_ORBIT = {
    "kakao-shokolad": "chocolate-bar",
    "orehovyy": "hazelnut",
    "dzhem-varene": "jam",
    "konditerskiy": "vanilla",
    "karamelnyy": "caramel",
    "travyanoy": "mint",
    "tsvetochnyy": "rose",
    "chaynyy": "tea-cup",
    "sadovye": "cherry",
    "tropicheskie": "mango",
    "tsitrusovye": "lemon",
    "kostochkovye-i-drugie": "peach",
    "suhofrukty": "fig",
    "yagody": "strawberry",
    "teplye-pryanosti": "ginger",
    "pryanosti": "cinnamon-stick",
    "vypechka": "croissant",
    "alkogolnye": "wine-glass",
}

ORBIT = {
    "nutty-cocoa": "coffee-bean",
    "kakao-shokolad": "chocolate-bar",
    "brauni": "brownie",
    "gorkiy-shokolad": "chocolate-bar",
    "kakao": "cocoa-powder",
    "molochnyy-shokolad": "chocolate-bar",
    "pudra-kakao": "cocoa-powder",
    "shokolad": "chocolate-bar",
    "shokolad-s-izyumom": "chocolate-bar",
    "shokoladnyj-keks": "brownie",
    "temnyy-shokolad": "chocolate-bar",
    "tertoe-kakao": "cocoa-powder",
    "orehovyy": "hazelnut",
    "arahis": "peanut",
    "arahisovaya-pasta": "peanut",
    "fistashka": "pistachio",
    "funduk": "hazelnut",
    "gretskiy-oreh": "walnut",
    "keshyu": "cashew",
    "kokos": "coconut",
    "lesnoj-oreh": "hazelnut",
    "makadamiya": "macadamia",
    "mindal": "almond",
    "zharenyj-mindalь": "almond",
    "orehi": "hazelnut",
    "orehovaya-pasta": "hazelnut",
    "pekan": "pecan",
    "solod": "biscuit",
    "zharenye-orehi": "hazelnut",
    "sweet": "honey",
    "dzhem-varene": "jam",
    "abrikosovyy-dzhem": "jam",
    "apelsinovyy-dzhem": "orange",
    "chernichnyy-dzhem": "blueberry",
    "ezhevichnyj-dzhem": "blueberry",
    "klubnichnyy-dzhem": "strawberry",
    "klyukvennyy-dzhem": "berry",
    "malinovyy-dzhem": "raspberry",
    "smorodinovyy-dzhem": "berry",
    "yablochnyj-dzhem": "apple",
    "konditerskiy": "vanilla",
    "dzhem": "jam",
    "grilyazh": "toffee",
    "jogurt": "yogurt",
    "martsipan": "almond",
    "nutella": "hazelnut",
    "pastila": "marshmallow",
    "slivki": "yogurt",
    "tsukaty": "orange",
    "vanil": "vanilla",
    "karamelnyy": "caramel",
    "iriska": "toffee",
    "karamel": "caramel",
    "klenovyy-sirop": "maple",
    "med": "honey",
    "melassa": "caramel",
    "nuga": "nougat",
    "sladkie-noty": "honey",
    "trostnikovyy-sahar": "sugar",
    "tsvetochnyy-med": "honey",
    "floral-tea": "tea-leaf",
    "travyanoy": "mint",
    "lemongrass": "lemongrass",
    "myata": "mint",
    "raznotrave": "tea-leaf",
    "shalfey": "sage",
    "sirop-tapinambura": "sugar",
    "smorodinovyy-list": "tea-leaf",
    "tsvetochnyy": "rose",
    "akatsiya": "jasmine",
    "cvetochnyj-chaj": "tea-cup",
    "cvetochnyy": "rose",
    "cvety": "rose",
    "gibiskus": "hibiscus",
    "karkade": "hibiscus",
    "lavanda": "lavender",
    "romashka": "chamomile",
    "roza": "rose",
    "zhasmin": "jasmine",
    "chaynyy": "tea-cup",
    "belyy-chay": "tea-cup",
    "chajnoe-telo": "tea-cup",
    "chernyy-chay": "tea-cup",
    "krasnyy-chay": "tea-cup",
    "roybush": "tea-cup",
    "smorodinovyj-chaj": "tea-leaf",
    "ulun": "tea-cup",
    "zelenyy-chay": "tea-leaf",
    "fruity": "cherry",
    "sadovye": "cherry",
    "barbaris": "berry",
    "chereshnya": "cherry",
    "chernaya-smorodina": "blueberry",
    "kryzhovnik": "berry",
    "oblepiha": "orange",
    "plodovye-frukty": "apple",
    "reven": "berry",
    "sliva": "plum",
    "smorodina": "berry",
    "zemlyanika": "strawberry",
    "tropicheskie": "mango",
    "arbuz": "melon",
    "dynya": "melon",
    "fejhoa": "kiwi",
    "grenadilla": "mango",
    "guava": "mango",
    "kivi": "kiwi",
    "lichi": "mango",
    "mango": "mango",
    "marakuyya": "mango",
    "nektarin": "peach",
    "papayya": "mango",
    "sladkij-fizalis": "orange",
    "tropicheskie-frukty": "mango",
    "zheltye-frukty": "mango",
    "tsitrusovye": "lemon",
    "apelsin": "orange",
    "bergamot": "lemon",
    "citrusy": "lemon",
    "greypfrut": "orange",
    "kumkvat": "orange",
    "laym": "lemon",
    "limon": "lemon",
    "mandarin": "orange",
    "pomelo": "lemon",
    "kostochkovye-i-drugie": "peach",
    "abrikos": "peach",
    "ananas": "pineapple",
    "granat": "pomegranate",
    "grusha": "apple",
    "kostochkovye-frukty": "peach",
    "persik": "peach",
    "vinograd": "grape",
    "vishnya": "cherry",
    "yabloko": "apple",
    "suhofrukty": "fig",
    "chernosliv": "plum",
    "finik": "fig",
    "inzhir": "fig",
    "izyum": "grape",
    "kuraga": "peach",
    "suhofrukty": "fig",
    "vyalenaya-vishnya": "cherry",
    "vyalenyy-banan": "banana",
    "yagody": "strawberry",
    "brusnika": "berry",
    "chernika": "blueberry",
    "ezhevika": "blueberry",
    "kalina": "berry",
    "klubnika": "strawberry",
    "klyukva": "berry",
    "krasnaya-smorodina": "berry",
    "lesnye-yagody": "blueberry",
    "malina": "raspberry",
    "ryabina": "berry",
    "shipovnik": "rose",
    "temnye-yagody": "blueberry",
    "vyalenye-yagody": "berry",
    "spicy-unique": "cinnamon-stick",
    "teplye-pryanosti": "ginger",
    "badyan": "star-anise",
    "imbir": "ginger",
    "kardamon": "cardamom",
    "kedr": "tea-leaf",
    "sladkie-spetsii": "cinnamon-stick",
    "pryanosti": "cinnamon-stick",
    "anis": "star-anise",
    "dubovoya-bochka": "barrel",
    "gvozdika": "clove",
    "koritsa": "cinnamon-stick",
    "muskatnyy-oreh": "nutmeg",
    "perets": "peppercorn",
    "pikantnyy": "peppercorn",
    "pryanosti": "cinnamon-stick",
    "specii": "clove",
    "tabak": "tobacco-leaf",
    "vypechka": "croissant",
    "biskvit": "biscuit",
    "kruassan": "croissant",
    "ovsyanoe-pechene": "biscuit",
    "pechene": "biscuit",
    "pirog": "bread",
    "rzhanoy-hleb": "bread",
    "vypechka": "croissant",
    "zharenye-zlaki": "biscuit",
    "alkogolnye": "wine-glass",
    "alkogolnyj": "wine-glass",
    "beloe-vino": "wine-glass",
    "heres": "wine-glass",
    "konyak": "whiskey",
    "krasnoe-vino": "wine-glass",
    "liker": "wine-glass",
    "portvejn": "wine-glass",
    "rom": "whiskey",
    "vermut": "wine-glass",
    "viski": "whiskey",
    "yablochnyj-sidr": "apple",
}

# Короткая фраза именно про эту ноту. Скрипт дописывает её до законченного абзаца.
FEEL = {
    "nutty-cocoa": "Тёплый фундамент чашки: орех, какао и мягкая горчинка, которую узнаёшь ещё до глотка.",
    "kakao-shokolad": "От молочной плитки до сухого какао — плотность, сладкая горчинка и долгое послевкусие.",
    "brauni": "Влажная шоколадная выпечка: какао, карамельная корочка и немного крошки.",
    "gorkiy-shokolad": "Сухая, взрослая горчинка какао без молочной сладости — она держит послевкусие.",
    "kakao": "Тёплый порошок какао: сухость, лёгкая пыльность и знакомая горчинка.",
    "molochnyy-shokolad": "Мягкая сладость молока и какао, округлая, почти десертная.",
    "pudra-kakao": "Сухая какао-пыль на языке: меньше сладости, больше аромата порошка.",
    "shokolad": "Ровная шоколадная база — ни слишком горькая, ни приторная.",
    "shokolad-s-izyumom": "Шоколад плюс тёмная ягодная сладость, как изюм в плитке.",
    "shokoladnyj-keks": "Мякиш с какао: сладкая крошка и тёплая выпечка.",
    "temnyy-shokolad": "Плотный тёмный какао, горчинка глубже, сладость только на краю.",
    "tertoe-kakao": "Маслянистое тёртое какао: гуще порошка и чуть сырее по вкусу.",
    "orehovyy": "Обжаренный орех: тёплый, чуть сладкий, с тонкой кожицей на послевкусии.",
    "arahis": "Жареный арахис — сладковатая шелуха и мягкое масло.",
    "arahisovaya-pasta": "Густая паста из обжаренного арахиса, липкая сладость и соль на крае.",
    "fistashka": "Свежая фисташка: зелёная сладость и лёгкая смолистая нота.",
    "funduk": "Жареный фундук — круглый, сладкий, с коричневой кожицей.",
    "gretskiy-oreh": "Грецкий орех: дубильная кожица, масло и лёгкая горчинка.",
    "keshyu": "Кешью мягче других орехов: сливочная сладость без остроты кожицы.",
    "kokos": "Белая мякоть кокоса — сладкая, чуть мыльная, очень узнаваемая.",
    "lesnoj-oreh": "Лесной орех ближе к фундуку: тёплый, обжаренный, домашний.",
    "makadamiya": "Макадамия — самая жирная и сливочная из ореховых нот.",
    "mindal": "Сладкий миндаль с тонкой марципановой горчинкой.",
    "zharenyj-mindalь": "Жареный миндаль: подрумяненная кожица, масло и марципановая сладость.",
    "orehi": "Сборная ореховая корзина: тепло, масло и лёгкая обжарка.",
    "orehovaya-pasta": "Густая ореховая паста — сладость и жирность остаются на нёбе.",
    "pekan": "Пекан слаще грецкого: карамельный орех, масло, почти ириска.",
    "solod": "Зерновой солод: хлебная сладость и лёгкая сухарь.",
    "zharenye-orehi": "Только что со сковороды: масло, соль и подрумяненная кожица.",
    "sweet": "Сладость здесь не сахар из пакетика, а варенье, карамель и выпечка.",
    "dzhem-varene": "Уваренная ягода: густая сладость, косточка и чуть варёная кожица.",
    "abrikosovyy-dzhem": "Абрикосовое варенье — солнечная мякоть и мягкая кислинка.",
    "apelsinovyy-dzhem": "Апельсиновый джем: цедра, сахара и горьковатая белая плёнка.",
    "chernichnyy-dzhem": "Тёмное черничное варенье, чернила и лесная сладость.",
    "ezhevichnyj-dzhem": "Ежевичный джем — глубже малины, с винной косточкой.",
    "klubnichnyy-dzhem": "Клубничный джем: знакомая конфета и чуть варёная ягода.",
    "klyukvennyy-dzhem": "Клюква с сахаром: кислинка не уходит, она просто прячется.",
    "malinovyy-dzhem": "Малиновое варенье — косточки, яркая сладость и розовый сок.",
    "smorodinovyy-dzhem": "Смородина, уваренная с сахаром: терпкость и тёмная сладость.",
    "yablochnyj-dzhem": "Яблочное повидло — мягкое, печёное, с коричной памятью даже без пряности.",
    "konditerskiy": "Кондитерская полка: ваниль, пастила, ореховая паста и крем.",
    "dzhem": "Просто джем — уваренная фруктовая сладость без конкретного сада.",
    "grilyazh": "Грильяж: орех в твёрдой карамели, хруст ещё слышен во вкусе.",
    "jogurt": "Молочный йогурт — мягкая кислота и сливочная сладость.",
    "martsipan": "Марципан: миндаль и сахарная пудра, чуть горький и очень сладкий.",
    "nutella": "Паста из обжаренного фундука и какао — густая, детская, десертная.",
    "pastila": "Пастила тает: яблочная сладость и воздушность, почти без кислоты.",
    "slivki": "Жирные сливки скругляют чашку и оставляют молочный след.",
    "tsukaty": "Цукаты — подсушенная цедра в сахаре, яркая и чуть жёсткая.",
    "vanil": "Ваниль сладкая и кремовая, она обнимает другие вкусы, а не спорит.",
    "karamelnyy": "Карамель, мёд и коричневый сахар: тёплая сладость без ягоды.",
    "iriska": "Ириска тянется: сливочная карамель и топлёное молоко.",
    "karamel": "Классическая карамель — сахар, доведённый до орехового цвета.",
    "klenovyy-sirop": "Кленовый сироп: древесная сладость, чище обычной карамели.",
    "med": "Мёд — цветочная сладость и лёгкая тягучесть на языке.",
    "melassa": "Меласса темнее сахара: патока, минеральность и горьковатый край.",
    "nuga": "Нуга: взбитый белок, мёд и орех, воздушная сладость.",
    "sladkie-noty": "Общая сладость без имени — сахар, который просто держит чашку.",
    "trostnikovyy-sahar": "Тростниковый сахар теплее белого: патока и лёгкая меласса.",
    "tsvetochnyy-med": "Светлый цветочный мёд — тоньше, душистее, меньше патоки.",
    "floral-tea": "Цветы, травы и чайный настой: тонкая чашка, которую легко перекричать горечью.",
    "travyanoy": "Сад после дождя: зелень, стебель и прохладный лист.",
    "lemongrass": "Лемонграсс — лимон без цедры, больше стебель и свежесть.",
    "myata": "Мята охлаждает даже тёплый кофе: лист, а не жвачка.",
    "raznotrave": "Смесь трав: сразу несколько листьев, ни один не главный.",
    "shalfey": "Шалфей суше и теплее мяты, с камфорным краем.",
    "sirop-tapinambura": "Овощная сладость сиропа: мягкая, чуть земляная, не медовая.",
    "smorodinovyy-list": "Лист смородины — зелёный, терпкий, дачный.",
    "tsvetochnyy": "Лепестки в чашке: духи, пыльца и сладкий нектар.",
    "akatsiya": "Акация — светлый цветочный мёд и белые гроздья.",
    "cvetochnyj-chaj": "Настой лепестков: мягче духов, ближе к чашке чая.",
    "cvetochnyy": "Просто цветы — общий душистый шлейф без одного бутона.",
    "cvety": "Букет целиком: сладкая пыльца и лёгкая парфюмерность.",
    "gibiskus": "Гибискус кислит и красится: клюквенный цветок, не роза.",
    "karkade": "Каркаде — тот же яркий кислый настой, суше и ягоднее.",
    "lavanda": "Лаванда душистая и мыльная, если её много; в меру — цветочное поле.",
    "romashka": "Ромашка: яблочный цветок, сено и спокойная сладость.",
    "roza": "Роза — лепесток, варенье и капля парфюма.",
    "zhasmin": "Жасмин сладкий и ночной: белый цветок на зелёном чае.",
    "chaynyy": "Чайный настой: лист, сушка и танин, а не ягода.",
    "belyy-chay": "Белый чай почти прозрачный: сухой лист и тонкая сладость.",
    "chajnoe-telo": "Чайное тело — ощущение настоя: танин, лист, мягкая терпкость.",
    "chernyy-chay": "Чёрный чай: тёплый лист, сушка и знакомая заварка.",
    "krasnyy-chay": "Красный чай глубже чёрного, с сухофруктом и деревом.",
    "roybush": "Ройбуш сладкий и древесный, без привычной чайной горечи.",
    "smorodinovyj-chaj": "Чай с листом смородины: зелень плюс тёмная ягода.",
    "ulun": "Улун — где-то между зелёным и чёрным: цветок, выпечка и лист.",
    "zelenyy-chay": "Зелёный чай: свежий лист, лёгкая трава и чистая чашка.",
    "fruity": "Фрукты и ягоды: кислота, сок и сладость, которые живут в самом зерне.",
    "sadovye": "Сад за калиткой: косточка, кожица и летний сок.",
    "barbaris": "Барбарис кислый и красный, почти конфета, но с косточкой.",
    "chereshnya": "Черешня слаще вишни: тёмная мякоть и мягкая косточка.",
    "chernaya-smorodina": "Чёрная смородина — чернила, лист и резкая сладость.",
    "kryzhovnik": "Крыжовник зелёный и кислый, с пушистой кожицей.",
    "oblepiha": "Облепиха маслянистая и кислая, как оранжевая ягода с куста.",
    "plodovye-frukty": "Общий садовый фрукт: сок, кожица, без одного имени.",
    "reven": "Ревень — зелёная кислинка стебля, не ягода.",
    "sliva": "Слива: тёмная кожица, мягкая мякоть и винная косточка.",
    "smorodina": "Смородина без цвета: терпкий сок и лист рядом.",
    "zemlyanika": "Земляника мельче клубники и душистее, с лесной сладостью.",
    "tropicheskie": "Тропический сок: спелость, аромат и мягкая кислота.",
    "arbuz": "Арбуз — водяная сладость и розовая мякоть, очень лёгкая.",
    "dynya": "Дыня медовая и мускусная, сладость без резкой кислоты.",
    "fejhoa": "Фейхоа: зелёная кожица, земляника и хвоя сразу.",
    "grenadilla": "Гренадилла кислее маракуйи, много сока и косточек.",
    "guava": "Гуава розовая и мускусная, сладкая мякоть и зелёная кожица.",
    "kivi": "Киви — яркая кислота, чёрные семена и зелёная свежесть.",
    "lichi": "Личи: розовая вода, виноград и цветочная сладость.",
    "mango": "Спелое манго — нектар, скипидар в меру и оранжевая мякоть.",
    "marakuyya": "Маракуйя резкая и тропическая: кислота, сок и аромат кожуры.",
    "nektarin": "Нектарин глаже персика: косточка, сок и меньше пушка.",
    "papayya": "Папайя мягкая и мускусная, сладость почти дыни.",
    "sladkij-fizalis": "Сладкий физалис — ягода в фонарике, кисло-сладкая.",
    "tropicheskie-frukty": "Смесь тропиков: сок, спелость и душный аромат.",
    "zheltye-frukty": "Жёлтые фрукты — общая солнечная сладость без одной косточки.",
    "tsitrusovye": "Цедра и сок: кислота звонкая, сладость только догоняет.",
    "apelsin": "Апельсин: сок, цедра и мягкая сладость мякоти.",
    "bergamot": "Бергамот — чай Эрл Грей: цедра, цветок и горьковатое масло.",
    "citrusy": "Цитрусы разом: цедра, сок и общая свежесть.",
    "greypfrut": "Грейпфрут горчит благородно: плёнка, сок и розовая кислота.",
    "kumkvat": "Кумкват едят с кожурой: сладкая цедра и кислая серединка.",
    "laym": "Лайм зеленее лимона и чуть острее, меньше сладости.",
    "limon": "Лимон — цедра впереди сока, свежо и чисто.",
    "mandarin": "Мандарин слаще апельсина, цедра мягкая и новогодняя.",
    "pomelo": "Помело суше грейпфрута: толстая плёнка и спокойная горчинка.",
    "kostochkovye-i-drugie": "Косточка, сок и летняя мякоть — персик, вишня, яблоко рядом.",
    "abrikos": "Абрикос: солнечная мякоть, кожица и мягкая кислинка.",
    "ananas": "Ананас колет язык: спелость, кислота и капля фермента.",
    "granat": "Гранат — зёрна, танин и винная кислость.",
    "grusha": "Груша нежная: белая мякоть, кожица и цветочная сладость.",
    "kostochkovye-frukty": "Общая косточка: сок у кожицы и миндальный край.",
    "persik": "Персик пушистый и сочный, сладость мякоти важнее кислоты.",
    "vinograd": "Виноград: кожица, сок и лёгкое вино ещё до бокала.",
    "vishnya": "Вишня кислее черешни, косточка слышнее.",
    "yabloko": "Яблоко — хруст, сок и зелёная или печёная кожица.",
    "suhofrukty": "Сухофрукт концентрирует сладость: меньше сока, больше патоки.",
    "chernosliv": "Чернослив тёмный, винный и очень сладкий.",
    "finik": "Финик — карамельная патока и липкая мякоть.",
    "inzhir": "Инжир: семена, мёд и варенье из кожицы.",
    "izyum": "Изюм — сушёный виноград, тёмная сладость без свежего сока.",
    "kuraga": "Курага ярче свежего абрикоса и слаще, с кислинкой на крае.",
    "vyalenaya-vishnya": "Вяленая вишня: косточка осталась, сок стал вареньем.",
    "vyalenyy-banan": "Вяленый банан — мягкая сладость и почти карамель.",
    "yagody": "Ягодная корзина: сок, косточка и кисло-сладкий край.",
    "brusnika": "Брусника мелкая и кислая, с лёгкой горчинкой листа.",
    "chernika": "Черника мягче смородины: пыль, чернила и тихая сладость.",
    "ezhevika": "Ежевика глубже малины, винная и косточковая.",
    "kalina": "Калина горчит и кислит, ягода поздняя и резкая.",
    "klubnika": "Клубника — самая знакомая ягода: сок, семена и конфета.",
    "klyukva": "Клюква звонко кислая, сладость приходит только следом.",
    "krasnaya-smorodina": "Красная смородина прозрачная и кислая, почти сок.",
    "lesnye-yagody": "Лесная смесь: сразу несколько мелких ягод и лист.",
    "malina": "Малина: косточки, розовый сок и яркая, не варёная сладость.",
    "ryabina": "Рябина терпкая, осенняя, с горчинкой кожицы.",
    "shipovnik": "Шиповник — кислый настой, цветок и витаминная кожица.",
    "temnye-yagody": "Тёмные ягоды разом: чернила, вино и сладость.",
    "vyalenye-yagody": "Вяленая ягода гуще свежей: патока вместо сока.",
    "yagody-note": "Ягоды как общее слово — сок без одного куста.",
    "spicy-unique": "Пряность, выпечка и бочковые оттенки — то, что делает чашку особенной.",
    "teplye-pryanosti": "Тёплые пряности греют, но не жгут: имбирь, бадьян, кардамон.",
    "badyan": "Бадьян — звёздочка аниса: сладкая лакрица и тепло.",
    "imbir": "Имбирь свежий и тёплый, острота мягкая, не перечная.",
    "kardamon": "Кардамон эвкалиптовый и сладкий, смола и цитрусовая кожура.",
    "kedr": "Кедр — хвоя, смола и орешек, прохладнее корицы.",
    "sladkie-spetsii": "Сладкие специи: корица и бадьян без перцового жара.",
    "pryanosti": "Пряный набор: кора, бутон, орех и перец в одной чашке.",
    "anis": "Анис слаще бадьяна и тоньше: семя, лакрица и тепло.",
    "dubovoya-bochka": "Дубовая бочка: ваниль дерева, танин и лёгкий дымок.",
    "gvozdika": "Гвоздика острая и сладкая, бутон слышен даже в малом количестве.",
    "koritsa": "Корица — сладкая кора, тепло и булочная сладость.",
    "muskatnyy-oreh": "Мускат тёплый и ореховый, чуть мыльный, если перебор.",
    "perets": "Перец сухой и острый, тепло остаётся в послевкусии.",
    "pikantnyy": "Пикантный край: не чистый перец, а тёплое покалывание.",
    "specii": "Специи разом — тепло, кора и бутон без одного имени.",
    "tabak": "Табак сухой и сладкий: лист, трубочный дым без горечи сигареты.",
    "vypechka": "Свежая выпечка: корочка, мякиш и тёплое тесто.",
    "biskvit": "Бисквит — яйцо, сахар и мягкий мякиш.",
    "kruassan": "Круассан: слоёное масло, корочка и сладкое тесто.",
    "ovsyanoe-pechene": "Овсяное печенье — зерно, масло и коричневый сахар.",
    "pechene": "Печенье: крошка, масло и лёгкая выпечка.",
    "pirog": "Пирог — тесто, начинка и подрумяненный край.",
    "rzhanoy-hleb": "Ржаной хлеб: корка, солод и лёгкая кислинка мякиша.",
    "zharenye-zlaki": "Жареные злаки — гречка и овёс на сковороде, сухие и сладкие.",
    "alkogolnye": "Винные и бочковые оттенки: фермент, дуб и сухофрукт, не сам напиток.",
    "alkogolnyj": "Общий алкогольный край: тепло, спиртуозность и сухофрукт.",
    "beloe-vino": "Белое вино — яблоко, цедра и прохладная кислость.",
    "heres": "Херес: орех, дрожжевая плёнка и сухая сладость.",
    "konyak": "Коньячный тон — дуб, сухофрукт и тёплое послевкусие.",
    "krasnoe-vino": "Красное вино: кожица винограда, танин и ягода.",
    "liker": "Ликёр сладкий и густой, ягода или трава в сиропе.",
    "portvejn": "Портвейн темнее вина: изюм, орех и креплёная сладость.",
    "rom": "Ром — тростниковая патока, дуб и тёплая сладость.",
    "vermut": "Вермут: вино плюс трава и полынная горчинка.",
    "viski": "Виски: зерно, бочка, ваниль дерева и лёгкий дым.",
    "yablochnyj-sidr": "Яблочный сидр — фермент, яблоко и лёгкие пузырьки во вкусе.",
}

HOW = {
    "nutty-cocoa": "Орех и какао чаще собирает обжарка, а не грядка. На средней и средне-тёмной сахара с аминокислотами дают пиразины — те самые орехово-шоколадные тона. Мытая обработка звучит чище, натуральная добавляет ягоду поверх какао.",
    "sweet": "Сладость приходит из карамелизации сахаров и из самого зерна: спелости, натуральной сушки, иногда долгой ферментации. Светлая обжарка оставляет мёд и фрукт, средняя уводит в ириску и варенье.",
    "floral-tea": "Цветы и чай живут в светлой обжарке: их легко сжечь. Часто это высокогорные мытые лоты, где в чашке остаются альдегиды и лёгкие терпены. Тёмная обжарка прячет их под карамелью.",
    "fruity": "Фрукт чаще сидит в самом зерне и в обработке. Мытая даёт чистый сок и цедру, натуральная — варенье и вино, хани и анаэробная ферментация делают ягоду гуще. Светлая и средне-светлая обжарка этот сок берегут.",
    "spicy-unique": "Пряность, выпечка и бочка — смесь обжарки и ферментации. Фенолы и продукты Майяра дают корицу, гвоздику и хлебную корочку. Натуральная обработка и чуть более длинное развитие усиливают их, не уводя в горечь.",
}

HOW_SUB = {
    "kakao-shokolad": "Какао поднимается позже ореха: средне-тёмное развитие, реакция Майяра и начало карамелизации. Если держать дольше, горчинка становится жжёной — это уже не шоколад. Натуральная сушка добавляет ягоду, мытая оставляет тон суше.",
    "orehovyy": "Орех любят средняя обжарка и пиразины. Светлее — он тонкий, как сырой миндаль; темнее — уходит в жжёное масло. Натуральные и хани-лоты часто слаще, мытые — чище и «суше» по ореху.",
    "dzhem-varene": "Варенье — это фрукт, который довели теплом: натуральная или долгая ферментация плюс средняя обжарка. Эфиры дают уваренную ягоду, а не свежий сок. Слишком тёмная обжарка заменяет джем карамелью.",
    "konditerskiy": "Кондитерские тона собираются на средней обжарке: ванильные альдегиды, карамелизация и ореховые пиразины. Мытая обработка делает их тоньше, натуральная — десертнее и тяжелее.",
    "karamelnyy": "Карамель рождается, когда сахара темнеют при обжарке. Средняя степень даёт ириску и мёд, тёмная — горькую жженку. В зерне с высокой сладостью и при натуральной сушке этот тон громче.",
    "travyanoy": "Травы слышны на светлой обжарке: зелёные альдегиды и лёгкие фенолы. Мытая обработка и плотное зерно держат лист чистым. Стоит уйти в карамель — и мята с шалфеем гаснут.",
    "tsvetochnyy": "Цветок любит светлую чашку и мытую обработку: терпены и жасминоподобные соединения не выдерживают долгого жара. Натуральная сушка может добавить мёд поверх лепестка.",
    "chaynyy": "Чайный лист — про сушку и танин. Часто это светлая или средняя обжарка, мытая или хани, когда в чашке остаётся настой, а не варенье. Тёмная степень превращает чай в какао.",
    "sadovye": "Садовый фрукт чаще у мытых и хани-лотов на светлой обжарке: яблочная и лимонная кислоты, эфиры косточки. Натуральная сушка делает тот же фрукт вареньем.",
    "tropicheskie": "Тропики громче на натуральной и анаэробной обработке: много эфиров, спелый сок, иногда мускус. Светлая обжарка сохраняет аромат, средняя добавляет карамель поверх манго.",
    "tsitrusovye": "Цедра — это светлая обжарка и мытая обработка: лимонная кислота и терпены кожуры. Натуральная сушка сдвигает цитрус к апельсиновому джему. Тёмная обжарка оставляет только горечь плёнки.",
    "kostochkovye-i-drugie": "Косточка и сок живут в светлой и средней чашке. Мытая обработка даёт чистое яблоко или персик, натуральная — компот. В миндальном крае косточки иногда слышны бензальдегиды.",
    "suhofrukty": "Сухофрукт усиливают натуральная сушка и чуть более длинная обжарка: сахара концентрируются, сок уходит, остаётся патока. Мытая чашка даёт тот же тон тише и чище.",
    "yagody": "Ягода — визитка светлой обжарки. Мытая даёт свежий сок, натуральная и анаэробная — вино и джем. Яблочная и лимонная кислоты держат сладость честной, без приторности.",
    "teplye-pryanosti": "Тёплые пряности часто из фенолов и продуктов Майяра на средней обжарке. Натуральная обработка делает их слаще, мытая — тоньше. Это не жжение перца, а тепло.",
    "pryanosti": "Кора, бутон и перец собираются на средней обжарке: фенолы, эвгенолоподобные тона, иногда лёгкая дымность развития. Натуральные лоты звучат прянее, мытые — суше и чище.",
    "vypechka": "Выпечка — это Майяр: средняя обжарка даёт корочку, солод и тесто. Зерно с хорошей сладостью и натуральная обработка добавляют сдобу. Пережар превращает хлеб в золу.",
    "alkogolnye": "Винные и бочковые тона любят ферментацию: натуральную, хани или долгую анаэробную. Эфиры дают вино и сухофрукт, а среднее развитие добавляет дубовую ваниль. Это вкус, не крепость.",
}

RESULT_HINT = {
    "sector": "Сначала понюхайте сухой помол, потом сделайте глоток, когда кофе уже не обжигает.",
    "subsector": "Сравните горячий глоток и глоток через минуту: направление должно остаться, а не раствориться в горечи.",
    "descriptor": "Поймайте ноту отдельно: вдох над чашкой, потом вкус на середине языка и послевкусие.",
}

CHECK = {
    "nutty-cocoa": "ореховая теплота и какао остаются, когда чашка остывает, а не только пахнут в паре",
    "sweet": "сладость чувствуется во вкусе, а не только как запах десерта",
    "floral-tea": "цветок или чай слышны на светлой чашке и не тонут в карамели",
    "fruity": "сок или варенье читаются отдельно от простой кислости",
    "spicy-unique": "тепло пряности или корочка выпечки остаётся в послевкусии",
}


def orbit_for(slug, sub_slug, sec_slug):
    if slug in ORBIT:
        return ORBIT[slug]
    if sub_slug and sub_slug in SUB_ORBIT:
        return SUB_ORBIT[sub_slug]
    return CATEGORY_ORBIT.get(sec_slug, ["coffee-bean"])[0]


def clip(text, limit):
    text = " ".join(text.split())
    if len(text) <= limit:
        return text
    cut = text[: limit - 1].rsplit(" ", 1)[0]
    return cut.rstrip(" ,;:—-") + "…"


def build_short(slug, name, parent):
    feel = FEEL.get(slug)
    if not feel:
        feel = f"{name} — отдельный штрих внутри «{parent}», тише названия и яснее, когда кофе чуть остынет."
    if feel[-1] not in ".!?":
        feel += "."
    return clip(feel, 220)


def build_how(slug, name, sec_slug, sub_slug):
    base = HOW_SUB.get(sub_slug) or HOW.get(sec_slug) or HOW.get(slug) or ""
    text = f"{name}. {base}"
    return clip(text, 360)


def build_result(slug, name, sec_slug, level):
    check = CHECK.get(sec_slug) or CHECK.get(slug) or "нота остаётся во вкусе, когда чашка чуть остынет"
    hint = RESULT_HINT[level if level in RESULT_HINT else "descriptor"]
    text = f"Проверьте так: {hint} У «{name}» получилось, если {check}."
    return clip(text, 320)


def main():
    notes = []
    missing = []
    for sec in TREE:
        notes.append({
            "id": sec["id"],
            "slug": sec["slug"],
            "level": "sector",
            "path": [sec["slug"]],
            "name": sec["name"],
            "short": build_short(sec["slug"], sec["name"], sec["name"]),
            "howInCoffee": clip(HOW[sec["slug"]], 360),
            "result": build_result(sec["slug"], sec["name"], sec["slug"], "sector"),
            "orbitElement": orbit_for(sec["slug"], None, sec["slug"]),
        })
        if sec["slug"] not in FEEL:
            missing.append(sec["slug"])
        for su in sec["subsectors"]:
            notes.append({
                "id": su["id"],
                "slug": su["slug"],
                "level": "subsector",
                "path": [sec["slug"], su["slug"]],
                "name": su["name"],
                "short": build_short(su["slug"], su["name"], sec["name"]),
                "howInCoffee": build_how(su["slug"], su["name"], sec["slug"], su["slug"]),
                "result": build_result(su["slug"], su["name"], sec["slug"], "subsector"),
                "orbitElement": orbit_for(su["slug"], su["slug"], sec["slug"]),
            })
            if su["slug"] not in FEEL:
                missing.append(su["slug"])
            for de in su["descriptors"]:
                slug = de["slug"]
                # slug yagody conflicts with subsector; descriptor uses its own feel key if present
                feel_key = slug
                if slug == "yagody" and "yagody" in FEEL and de["hideFromWheel"]:
                    feel_key = "yagody-note" if "yagody-note" in FEEL else slug
                notes.append({
                    "id": de["id"],
                    "slug": slug,
                    "level": "descriptor",
                    "path": [sec["slug"], su["slug"], slug],
                    "name": de["name"],
                    "short": build_short(feel_key if feel_key in FEEL else slug, de["name"], su["name"]),
                    "howInCoffee": build_how(slug, de["name"], sec["slug"], su["slug"]),
                    "result": build_result(slug, de["name"], sec["slug"], "descriptor"),
                    "orbitElement": orbit_for(slug, su["slug"], sec["slug"]),
                })
                if feel_key not in FEEL and slug not in FEEL:
                    missing.append(slug)

    payload = {"tree": TREE, "notes": notes, "categoryOrbit": CATEGORY_ORBIT}
    out = ROOT / "flavor-wheel" / "flavor-data.json"
    out.write_text(json.dumps(payload, ensure_ascii=False, separators=(",", ":")), encoding="utf-8")
    print("notes", len(notes), "bytes", out.stat().st_size)
    if missing:
        print("MISSING", len(missing))
        print("\n".join(missing))
    else:
        print("all feels present")
    # length audit
    over = [n["slug"] for n in notes if len(n["short"]) > 220 or len(n["howInCoffee"]) > 360 or len(n["result"]) > 360]
    print("over limit", over)


if __name__ == "__main__":
    main()
